server:
  port: 9004 #服务访问端口号

#spring:
#  application:
#    name: tensquare-article #服务名称
#  datasource: #数据库连接四大属性
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.0.222:3306/tensquare_article?characterEncoding=utf-8
#    username: root
#    password: root
spring:
  application:
    name: tensquare-article
  #配置数据源类型
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.222:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: root
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
  data:
    mongodb:
      host: 192.168.0.222
      database: commentdb
  redis:
    host: 192.168.0.222


# Mybatis-Plus 配置
mybatis-plus:
# mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tensquare.article.pojo
  global-config:
    id-type: 1 #0:数据库ID自增 1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用